CREATE TABLE IF NOT EXISTS sports (id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS equipment (id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL);
CREATE TABLE IF NOT EXISTS sport_equipment (id SERIAL PRIMARY KEY, sport_id INT REFERENCES sports(id) ON DELETE CASCADE, equipment_id INT REFERENCES equipment(id) ON DELETE CASCADE, display_name VARCHAR(150) NOT NULL, total_quantity INT NOT NULL, remaining_quantity INT NOT NULL);
CREATE TABLE IF NOT EXISTS requested_equipment (id SERIAL PRIMARY KEY, student_id VARCHAR(50) NOT NULL, equipment_id INT REFERENCES sport_equipment(id) ON DELETE CASCADE, quantity INT NOT NULL DEFAULT 1, pickup_time VARCHAR(50) NOT NULL, status VARCHAR(20) DEFAULT 'issued', requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
